hmLoadTopic({
hmKeywords:"",
hmTitle:"Catalog service",
hmDescription:"The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new device types or changes to...",
hmPrevLink:"index.html",
hmNextLink:"authentication-and-authorizato.html",
hmParentLink:"index.html",
hmBreadCrumbs:"<a href=\"index.html\">Neutral backend infrastructure<\/a>",
hmTitlePath:"Neutral backend infrastructure > Catalog service",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Catalog service<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new device types or changes to existing device types.The HsM Catalog Service is part of the HsM Neutral back-end infrastructure. The meta data served by the Catalog Service is solely modified by Hagleitner. Read-only access to the meta data in the Catalog Service is however not restricted. The Catalog Service does not provide a user interface but is intended to be used by other software systems.<\/p>\n\r<p class=\"p_Normal\">The meta data managed by the Catalog Service contains (not necessarily complete list):<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Unique device type IDs: Each HsM device type has a unique ID (a global unique identifier), the catalog service is the place where these IDs are assigned on registration of new device types.<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Structural models of device types: Including the device’s component placeholder and compound member placeholders.<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Definition of the resource instances (sensors and settings) exposed by firmware components within the device type. This includes a definition of the resource instances data type, validation rules, display hints etc.<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Naming of the device type, its components, etc. in multiple languages<\/p><p class=\"p_Normal\">The Catalog service builds upon the way we define devices in HSM.<\/p>\n\r<p class=\"p_Normal\">The digital twins of HSM devices are much more than an ID and the associated telemetry data. Digital twins in HSM represent all characteristics of devices that allow HSM to form a fully digital lifecycle for each device. The core concept that defines how digital twins are represented in HSM is the concept of a device being a hierarchically structured conglomerate of components and sub-components.<\/p>\n\r"
})
