hmLoadTopic({
hmKeywords:"",
hmTitle:"Component types",
hmDescription:"Component types are used in device types to specify which kind of components can be used to fill a component placeholder. Besides the basic type of the component, component...",
hmPrevLink:"lifecycle-state.html",
hmNextLink:"placeholder-visibility.html",
hmParentLink:"cats.html",
hmBreadCrumbs:"<a href=\"neutral-backend-infrastructure.html\">Neutral backend infrastructure<\/a> &gt; <a href=\"cats.html\">Catalog service<\/a>",
hmTitlePath:"Neutral backend infrastructure > Catalog service > Component types",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Component types<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Component types are used in device types to specify which kind of components can be used to fill a component placeholder. Besides the basic type of the component, component types also define multiple characteristics that a component type has.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Component type variant<\/p>\n\r<p class=\"p_Normal\">For a component any number of component variants can be registered. I.e. component type variants are interchangable on physical devices.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Any component type must have at least one variant.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Component type variant version<\/p>\n\r<p class=\"p_Normal\">For a component type any number of variant versions can be registered. A component placeholder in a device is typed with a component type only. Physical devices fill this placeholder with a specific component type variant version.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Any component type variant must have at least one version. Versions of component type variants must have a unique version identifier. Version identifiers must be comparable.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Components, Variants &amp; Versions<\/p>\n\r<p class=\"p_Normal\">Component types are used in device type definitions to specifiy components and their structure in devices that adhere to this device type definition. Components can come in different variants, e.g. a white or a blue shell, all of them being interchangeable. The device type definition does not specify the exact variant to be used.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">A digital twin of a device (the device) always has a reference to its device type and stores information about the instances of components actually built into the device.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">A device\'s components may change over its lifetime. Optional components can be added or removed, mandatory components can be exchanged.<\/p>\n\r<p class=\"p_Normal\">A device type describes the components that are used in instances of this device type. However it does not describe the variant and version of the used components.<\/p>\n\r<p class=\"p_Normal\">A device describes which components (in which variation and version) a physical device actually consists of.<\/p>\n\r"
})
