hmLoadTopic({
hmKeywords:"",
hmTitle:"Gateway configuration",
hmDescription:"In most cases it will be necessary to configure the gateway\'s network interface properties so that it can connect to the HsM HsM Backend via your local area network (LAN) or...",
hmPrevLink:"installing-a-device.html",
hmNextLink:"cuapp-gwconf-preconditions.html",
hmParentLink:"cuapp.html",
hmBreadCrumbs:"<a href=\"frontends.html\">Frontends<\/a> &gt; <a href=\"cuapp.html\">Xibu App<\/a>",
hmTitlePath:"Frontends > Xibu App > Gateway configuration",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Gateway configuration<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">In most cases it will be necessary to configure the gateway\'s network interface properties so that it can connect to the HsM HsM Backend via your local area network (LAN) or wireless local area network (WLAN). The Xibu App provides a <span class=\"f_Term\">network configuration wizard<\/span> that will guide you through this configuration process. <\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.44; padding: 0 0 0 0; margin: 0.3750rem 0 0.2500rem 0;\"><table class=\"Box\" >\n\r<tr class=\"Box\">\n\r<td class=\"Box\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">Note<\/span>: The gateway configuration wizard covers the configuration for most network environments. If you have to configure your gateway for a very special network environment you might might need to use the gateway\'s <a href=\"hsmd-gwlan-accessingconfiguration-webpage.html\" class=\"topiclink\">web page<\/a> or <a href=\"hsmd-gwlan-accessingconfiguration-ssh.html\" class=\"topiclink\">SSH<\/a>.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">To start the network configuration wizard, go to the gateway\'s <a href=\"cuapp-devicedetailscreen.html\" class=\"topiclink\">device detail screen<\/a>, there to the <span class=\"f_UIElements\">Settings<\/span> tab and Select <span class=\"f_UIElements\">Configure network connection<\/span>. The network configuration wizard guides you through multiple configuration steps:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_UIElements\"><a href=\"cuapp-gwconf-preconditions.html\" class=\"topiclink\">Prepare the gateway<\/a><\/span>: In this step you check the <a href=\"cuapp-gwconf-preconditions.html\" class=\"topiclink\">preconditions<\/a> for configuring the gateway<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_UIElements\"><a href=\"cuapp-gwconf-connecting-to-gateway.html\" class=\"topiclink\">Connect to gateway<\/a><\/span>: This step establishes a network connection between your mobile device and the gateway.<\/p><p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin-left: 0;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_UIElements\"><a href=\"connect-to-network.html\" class=\"topiclink\">Configure network connection<\/a><\/span>: This step does the actual configuration of the gateway\'s network interface properties, i.e. it configures the gateway so that it will be part of your LAN or WLAN.<\/p>"
})
