hmLoadTopic({
hmKeywords:"",
hmTitle:"Availability",
hmDescription:"Generally HsM aims at a 24\/7\/365 availability. For technical reasons it is however not possible to provide 100% availability and therefore the availability of the HsM system is...",
hmPrevLink:"operations2.html",
hmNextLink:"data-loss-protection.html",
hmParentLink:"operations2.html",
hmBreadCrumbs:"<a href=\"backend-infrastructure.html\">Backend infrastructure<\/a> &gt; <a href=\"operations2.html\">Service-level<\/a>",
hmTitlePath:"Backend infrastructure > Service-level > Availability",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Availability<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Generally HsM aims at a 24\/7\/365 availability. For technical reasons it is however not possible to provide 100% availability and therefore the availability of the HsM system is defined as follows. <\/p>\n\r<p class=\"p_Normal\">All the numbers describing the availability of the system mentioned below are meant as design goals and define the development efforts Hagleitner has put into robustness and resilience of HsM. Exceptional circumstances and dependencies on external systems (e.g. Azure) can still lead to a decreased availability<span class=\"f_Term\" style=\"font-size: 1.10rem; font-family: Calibri,Vectora,\'Droid Sans\',\'Open Sans\',Frutiger,sans-serif; font-style: normal;\">.<\/span><\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">General Availability<\/span><\/h1>\n\r<p class=\"p_Normal\">HsM is designed for a general availability of 99.59 %, i.e. less than 36 h downtime per year. Additionally a single consecutive downtime shall shall not exceed 3 h, i.e. maximal 12 downtimes per year with less than 3 h each.<\/p>\n\r<p class=\"p_Normal\">During these downtimes the HsM is not available for any user and no part of the system can be used While HsM implements some precautions that even during these downtimes users trying to access the system will be nicely informed, this cannot be guaranteed.<\/p>\n\r<p class=\"p_Normal\">The backend infrastructure of HsM follows a microservice design pattern which means that some micro services might be down while all others are still working. Therefore separate service-levels are defined for each service. I.e. the 99.59 % general availability does not necessarily mean that all functionality is available in these 99.59 % of time.<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Planned downtimes<\/span><\/h1>\n\r<p class=\"p_Normal\">Planned downtimes with upfront &nbsp;information to the user about this downtime and meaningful information to users trying to access these systems during the downtime are excluded from the above availability of 99.59 %.<\/p>\n\r<p class=\"p_Normal\">Planned downtimes are carefully chosen by Hagleitner to be mostly in times when  HsM is least used.<\/p>\n\r"
})
