pageinfo = [[1629687819,0,0,0,null],
	[1629687806,0,0,0,null],
	[1613408441,0,0,0,null],
	[1614835128,0,0,0,null],
	[1613408439,0,0,0,null],
	[1617250701,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687820,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687802,0,0,0,null],
	[1620197330,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687805,0,0,0,null],
	[1628590719,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687815,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687814,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687804,0,0,0,null],
	[1613408249,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687802,0,0,0,null],
	[1613375395,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687807,0,0,0,null],
	[1624902507,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687808,0,0,0,null],
	[1613964798,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687807,0,0,0,null],
	[1614802811,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687807,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687803,0,0,0,null],
	[1619632146,0,0,0,null],
	[1619632145,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687801,0,0,0,null],
	[1628590720,0,0,0,null],
	[1628590720,0,0,0,null],
	[1615413792,0,0,0,null],
	[1613408441,0,0,0,null],
	[1629687803,0,0,0,null],
	[1613375396,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687805,0,0,0,null],
	[1613408257,0,0,0,null],
	[1629687801,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687800,0,0,0,null],
	[1616626126,0,0,0,null],
	[1629687799,0,0,0,null],
	[1619046228,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687816,0,0,0,null],
	[1616626125,0,0,0,null],
	[1616626126,0,0,0,null],
	[1619632133,0,0,0,null],
	[1613115698,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687809,0,0,0,null],
	[1619177611,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687810,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687809,0,0,0,null],
	[1624371517,0,0,0,null],
	[1617250701,0,0,0,null],
	[1613408255,0,0,0,null],
	[1613408439,0,0,0,null],
	[1613408440,0,0,0,null],
	[1613408440,0,0,0,null],
	[1613408255,0,0,0,null],
	[1613115698,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687809,0,0,0,null],
	[1629687810,0,0,0,null],
	[1615867391,0,0,0,null],
	[1613408441,0,0,0,null],
	[1611559838,0,0,0,null],
	[1619177611,0,0,0,null],
	[1629687820,0,0,0,null],
	[1619046228,0,0,0,null],
	[1614025131,0,0,0,null],
	[1613112693,0,0,0,null],
	[1629687803,0,0,0,null],
	[1628590720,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613375395,0,0,0,null],
	[1619046227,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687799,0,0,0,null],
	[1613408252,0,0,0,null],
	[1614708228,0,0,0,null],
	[1629687804,0,0,0,null],
	[1613375396,0,0,0,null],
	[1613112693,0,0,0,null],
	[1629687819,0,0,0,null],
	[1613115702,0,0,0,null],
	[1613408252,0,0,0,null],
	[1613112700,0,0,0,null],
	[1613408251,0,0,0,null],
	[1629687799,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687812,0,0,0,null],
	[1620326921,0,0,0,null],
	[1629687811,0,0,0,null],
	[1629687810,0,0,0,null],
	[1629687811,0,0,0,null],
	[1616156305,0,0,0,null],
	[1629687811,0,0,0,null],
	[1616156304,0,0,0,null],
	[1629687811,0,0,0,null],
	[1620595129,0,0,0,null],
	[1629687811,0,0,0,null],
	[1629687810,0,0,0,null],
	[1629687811,0,0,0,null],
	[1629687811,0,0,0,null],
	[1620621203,0,0,0,null],
	[1629687811,0,0,0,null],
	[1629687810,0,0,0,null],
	[1629687810,0,0,0,null],
	[1620326920,0,0,0,null],
	[1620326920,0,0,0,null],
	[1616156304,0,0,0,null],
	[1616156304,0,0,0,null],
	[1616626126,0,0,0,null],
	[1620273802,0,0,0,null],
	[1629687810,0,0,0,null],
	[1613408439,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687820,0,0,0,null],
	[1628590719,0,0,0,null],
	[1629687820,0,0,0,null],
	[1613375395,0,0,0,null],
	[1629687811,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687816,0,0,0,null],
	[1619166836,0,0,0,null],
	[1619066905,0,0,0,null],
	[1629687817,0,0,0,null],
	[1613408439,0,0,0,null],
	[1619046227,0,0,0,null],
	[1619166836,0,0,0,null],
	[1619166837,0,0,0,null],
	[1619632133,0,0,0,null],
	[1629687820,0,0,0,null],
	[1613375396,0,0,0,null],
	[1614708223,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629617628,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687813,0,0,0,null],
	[1629687812,0,0,0,null],
	[1629687799,0,0,0,null],
	[1613112701,0,0,0,null],
	[1629687816,0,0,0,null],
	[1615413791,0,0,0,null],
	[1624515499,0,0,0,null],
	[1629687814,0,0,0,null],
	[1614919717,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687813,0,0,0,null],
	[1616156304,0,0,0,null],
	[1613375396,0,0,0,null],
	[1629687818,0,0,0,null],
	[1613115698,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687801,0,0,0,null],
	[1613375396,0,0,0,null],
	[1629687808,0,0,0,null],
	[1629687801,0,0,0,null],
	[1629687801,0,0,0,null],
	[1613375395,0,0,0,null],
	[1629687816,0,0,0,null],
	[1629687818,0,0,0,null],
	[1629687814,0,0,0,null],
	[1628590719,0,0,0,null],
	[1616626125,0,0,0,null],
	[1629687816,0,0,0,null],
	[1613408440,0,0,0,null],
	[1613408440,0,0,0,null],
	[1629687802,0,0,0,null],
	[1619632142,0,0,0,null],
	[1613408439,0,0,0,null],
	[1629687799,0,0,0,null],
	[1613408251,0,0,0,null],
	[1614708226,0,0,0,null],
	[1613408440,0,0,0,null],
	[1613112701,0,0,0,null],
	[1628590719,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687805,0,0,0,null],
	[1619632133,0,0,0,null],
	[1613375396,0,0,0,null],
	[1626302028,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687803,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302028,0,0,0,null],
	[1626302028,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1626302029,0,0,0,null],
	[1613408441,0,0,0,null],
	[1613408439,0,0,0,null],
	[1619166836,0,0,0,null],
	[1613408256,0,0,0,null],
	[1629687804,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687819,0,0,0,null],
	[1629687801,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687801,0,0,0,null],
	[1629687815,0,0,0,null],
	[1613112701,0,0,0,null],
	[1619166836,0,0,0,null],
	[1629687810,0,0,0,null],
	[1625037496,0,0,0,null],
	[1629687815,0,0,0,null],
	[1613408439,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687818,0,0,0,null],
	[1613115698,0,0,0,null],
	[1628590719,0,0,0,null],
	[1612961533,0,0,0,null],
	[1629687820,0,0,0,null],
	[1613115698,0,0,0,null],
	[1629687802,0,0,0,null],
	[1629687816,0,0,0,null],
	[1628590720,0,0,0,null],
	[1629687810,0,0,0,null],
	[1629687806,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687809,0,0,0,null],
	[1613375396,0,0,0,null],
	[1629687817,0,0,0,null],
	[1619046227,0,0,0,null],
	[1614708227,0,0,0,null],
	[1613408256,0,0,0,null],
	[1629687806,0,0,0,null],
	[1628590719,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687805,0,0,0,null],
	[1629687810,0,0,0,null],
	[1628590719,0,0,0,null],
	[1629687801,0,0,0,null],
	[1613408441,0,0,0,null],
	[1611559838,0,0,0,null],
	[1619134421,0,0,0,null],
	[1629687799,0,0,0,null],
	[1629687809,0,0,0,null],
	[1613375396,0,0,0,null],
	[1629617621,0,0,0,null],
	[1613408440,0,0,0,null],
	[1629687800,0,0,0,null],
	[1629687815,0,0,0,null],
	[1616626125,0,0,0,null],
	[1629687801,0,0,0,null],
	[1613115698,0,0,0,null],
	[1629687799,0,0,0,null],
	[1629687800,0,0,0,null],
	[1614708227,0,0,0,null],
	[1614708228,0,0,0,null],
	[1614708228,0,0,0,null],
	[1614708223,0,0,0,null],
	[1629687804,0,0,0,null],
	[1613408256,0,0,0,null],
	[1629687817,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687803,0,0,0,null],
	[1629687801,0,0,0,null],
	[1619046228,0,0,0,null],
	[1613408256,0,0,0,null]];
pagedata = [ ["./4plus.html","4Plus (50-01)","Additional to the content parts described in Device QR Codes this content type also includes an EUI-48 network Id. This content type is used for 4...","./images/zoomimage.jpg"],
["./active-directory-groups-to-rol.html","Active directory groups to role members","Enter topic text here.","./images/zoomimage.jpg"],
["./adaptive-date-interval-specifi.html","Adaptive date interval definition","Adaptive date intervals definitions are not statically defined date intervals but rather use offsets and other settings to provide a blueprint for...",""],
["./administrators-guide.html","Administrator&#39;s Guide","Installation Maintenance",""],
["./administrators-guide2.html","Administrator&#39;s Guide","Enter topic text here.",""],
["./administrators-guide_2.html","Administrator&#39;s Guide","Installation Maintenance","./images/zoomimage.jpg"],
["./analog-and-auxiliary-(50-03).html","Analog and auxiliary (50-03)","This content type just comes with the content parts described in Device QR Codes. This content type is used for devices that do not support any ne...","./images/zoomimage.jpg"],
["./article-numbers.html","Article numbers","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./authentication--authorization.html","Authentication &#38; Authorization","Enter topic text here.","./images/zoomimage.jpg"],
["./authentication--authorization2.html","Authentication &#38; Authorization","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./authentication-and-authorizato.html","Authentication","The HsM Catalog Service Browse API allows anonymous access to all its endpoints. To get data from these browse endpoints the client however has to...","./images/zoomimage.jpg"],
["./authentication.html","Authentication","Users &#38; Organizations","./images/zoomimage.jpg"],
["./authorization.html","Authorization","The entities managed through the Catalog Service’s Admin API are protected using policies","./images/zoomimage.jpg"],
["./authorization2.html","Authorization","HsM has three primary security components that are used to define what data users have access to and what operations users are permitted to perform:","./images/zoomimage.jpg"],
["./autzorization-and-uthenticatio.html","Authorization and Authentication","Enter topic text here.","./images/zoomimage.jpg"],
["./backend-infrastructure.html","Backend infrastructure","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./backup--recovery.html","Backup &#38; Recovery","C2DD persists data in a SQL database with full backup concept.","./images/zoomimage.jpg"],
["./c2dd--operations.html","Operations","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./c2dd-backup-recovery.html","Backup &#38; Recovery","The general notes on data loss protection apply to this service.","./images/zoomimage.jpg"],
["./c2dd-eventual-consistency.html","Eventual consistency","Data Link Monitoring Service The Cloud To Device Distribution Service caches topolgy information for a limited amount of time (30 minutes)","./images/zoomimage.jpg"],
["./c2dd-inter-service-communication.html","Inter service communication","Cloud To Device Distribution Service uses the Inter Service Communication Service to publish information when a task has reached a final state.&#38;nb...","./images/zoomimage.jpg"],
["./c2dd-internationalization.html","Internationalization","Language: Any input and output is in English (US) Culture: Any input and output is in English (US) Date time: Handles date and time values in UTC ...","./images/zoomimage.jpg"],
["./c2dd-limitations.html","Limitations","Tasks might result in duplicated processes on gateway and therefore duplicated actions on the recipient device. E.g. The Cloud To Device Distribut...","./images/zoomimage.jpg"],
["./c2dd-message-types.html","Task types","The Cloud To Device Distribution Service can manage different types of tasks. Each task is adressed to one specific recipient (a gateway device or...","./images/zoomimage.jpg"],
["./c2dd-messgetype-firmware-update.html","Initiate Firmware Update","{     \"messageId\": \"a1baa49f-70dc-4266-b1e6-1a43707605456\",     \"recipientNetworkId\":\"142fe...","./images/zoomimage.jpg"],
["./c2dd-messgetype-readresource.html","Read resource instance values","This task type is used to advice the recipient to send the values of specified resource instances. The resource instance values will be sent by th...","./images/zoomimage.jpg"],
["./c2dd-messgetype-writeresource.html","Write resource instance values","Resource instance messages advice the gateway to set resources values on the specified recipient device to the given values. ","./images/zoomimage.jpg"],
["./c2dd-monitoring.html","Monitoring","Enter topic text here.","./images/zoomimage.jpg"],
["./c2dd-operation-principle.html","Basic","The Cloud To Device Distribution Service   The Cloud To Device Distribution Service accepts different types of tasks via its REST API. Each t...","./images/zoomimage.jpg"],
["./c2dd-service-dependencies.html","Service dependencies and resilience","Cloud To Device Distribution Service Database Type of dependency: Live, non resilient The Cloud To Device Distribution Service internally uses a d...","./images/zoomimage.jpg"],
["./c2dd-sla.html","SLA","Availability Generally Cloud To Device Distribution Service aims at a 24/7/365 availability. For technical reasons it is however not possible to p...","./images/zoomimage.jpg"],
["./c2dd.html","Cloud To Device Distribution Service","The Cloud To Device Distribution Service manages tasks that initiate different types of actions on HsM devices (BLE-networked devices as well as g...","./images/zoomimage.jpg"],
["./cat-resource-instance-equivalents.html","Resource instance equivalents","Resource instance equivalents are global catalog elements that are used to link resource instances with the same logical meaning across different ...","./images/zoomimage.jpg"],
["./catalog-element-description.html","Catalog Element Description","For many entities managed in the Catalog Service the Catalog Service stores descriptive information in form of catalog element descriptions. A cat...","./images/zoomimage.jpg"],
["./catalog-service.html","HsM Catalog Service","The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new dev...",""],
["./cats-device-type.html","Device type","A device type is the scheme that defines the logical and physical structure of HsM device. This includes the components that are used for instance...","./images/zoomimage.jpg"],
["./cats.html","Catalog service","The HsM Catalog Service provides meta data about all HsM device types. This meta data is used in many areas of HsM to dynamically adapt to new dev...","./images/zoomimage.jpg"],
["./client-service.html","Client Service","Enter topic text here.",""],
["./clse-device-installation.html","Device installation","Linking (the digital twin of) a device to a specific room within the location tree of a customer is called device installation. Releasing the link...","./images/zoomimage.jpg"],
["./clse-devicefilter-compounddevicehandling.html","Handling of compound devices","The set of devices that results from an execution of a device filter will be enriched with all compound member and compound devices.","./images/zoomimage.jpg"],
["./clse-devicefilter-executionscope.html","Execution Scope","When a device filter is executed, it is always executed in a specific scope. This execution scope defines the base set of devices to which the fil...","./images/zoomimage.jpg"],
["./clse-devicefilter-logicaloperators.html","Logical operators","Device filters support following logical operators:","./images/zoomimage.jpg"],
["./clse-devicefilter-scopeavailability.html","Scope availability ","Some device filter term types are only useful when the device filter including that term type is executed in a specific scope. E.g. a term of type...","./images/zoomimage.jpg"],
["./clse-devicefilter-termtypeavailability.html","Term type availability","Some device filter terms are restricted to HsM users with specific permissions.","./images/zoomimage.jpg"],
["./clse-devicefilter-validity-constraints.html","Validity constraints","Several constraints must be fulfilled for a device filter to be valid. This includes constraints that apply to the structure of the expression tre...","./images/zoomimage.jpg"],
["./clse-devicefilter.html","Device filter","A device filter is a logical expression that can be applied to the devices managed by the Client Service to filter for a subset of those devices. ...","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-birthdate.html","Birth date","Filters by birth date of the device (or to be exact by the birth date of the digital twin).","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-compounddevicestatus.html","Compound device status","Compound member devices are part of the base set of devices to which device filters are applied, i.e. in the base set of devices to which the devi...","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-customer.html","Customer","Filters for devices assigned to a given customer. Settings Setting Description Customer Only devices assigned to that customer will pass the filte...","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-devicetype.html","Device type","Filters for devices that are of one of the given device types.","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-installationdate.html","Installation date","Filters for devices based on their installation date, i.e. the date when the device was installed at a specific location.","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-latestequivalentresourceinstancevalue.html","Latest equivalent resource instance value","Enter topic text here.",""],
["./clse-devicefiltertermtype-latestresourceinstanceupdate.html","Latest resource instance update","Filters for devices whose latest modification or update on any of its resource instance is within the specified date interval. ","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-latestresourceinstancevalue.html","Latest resource instance value","Filters devices by their latest reported resource instance values. ","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-location.html","Location","Filters for devices that are installed at specific locations with in the location tree of customers.","./images/zoomimage.jpg"],
["./clse-devicefiltertermtype-organization.html","Organization","Filters for devices assigned to customers within an given organization.","./images/zoomimage.jpg"],
["./clse-devicefiltertermtypes.html","Device filter term types","Device filter term types are predefined building blocks for device filters. Term types can have settings and have their own validation rules.","./images/zoomimage.jpg"],
["./clse-saved-device-filters.html","Saved device filters","Device filters can be stored on the HsM Client Service for reuse.",""],
["./clse-stored-device-filters.html","Stored device filters","Device filters can be stored on the Client Service for reuse.","./images/zoomimage.jpg"],
["./clse-validating-device-filters.html","Validating device filters","The Client Service provides the possibility to validate a device filter and report the result so this validation in a human readable form. This va...","./images/zoomimage.jpg"],
["./clse.html","Client Service","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./coap.html","Configuration app","Enter topic text here.","./images/zoomimage.jpg"],
["./combining-devices.html","Combining devices","Compound devices can either be created by the Digital Twin registration agent when the device is first registered, or they can be created through ...","./images/zoomimage.jpg"],
["./comm-ble-advertisement.html","Advertisement","HsM BLE-networked devices send out advertising packages notify other BLE devices (including HsM gateway devices) about their existence. The advert...","./images/zoomimage.jpg"],
["./comm-ble.html","BLE Communication","In HsM BLE-networked devices are communicate with HsM gateway devices ","./images/zoomimage.jpg"],
["./comm-date-interval-specification-adaptive.html","Adaptive date interval specification","Adaptive date intervals specifications are not based on Start and End but rather specify an algorithm to calculate a Start and End from the curren...","./images/zoomimage.jpg"],
["./comm-date-interval-specification-predefinedadaptive.html","Predefined adaptive date intervals","For easier specification of adaptive date intervals the Client Service provides some predefined date intervals","./images/zoomimage.jpg"],
["./comm-date-interval-specification-static.html","Static date interval specification","A static date interval specification is a date interval specification based on a fixed start and end date time offset.","./images/zoomimage.jpg"],
["./comm-date-interval-specification.html","Date interval specification","Date interval specifications are used to filter or query timestamped data based on given start date and end date.  Date interval specificatio...","./images/zoomimage.jpg"],
["./comm-serial-numbers-v1.html","Version 1","Version 1 serial numbers are of variable length. Serial numbers of this version match the Regex ([0-9]{2})(0[0-9]&#124;1[012])([012][0-9]&#124;3[01])([0-9]{...","./images/zoomimage.jpg"],
["./comm-serial-numbers-v2.html","Version 2","Version 2 serial numbers are of fixed length. Serial numbers of this version match the regex (2[0-9]{3})-([0-9]{2})(0[0-9]&#124;1[012])([012][0-9]&#124;3[01...","./images/zoomimage.jpg"],
["./comm-serial-numbers-v3.html","Version 3","Version 3 of HsM serial numbers are fixed length serial numbers. This serial number contains digits and letters. The serial number is case insensi...","./images/zoomimage.jpg"],
["./comm-serial-numbers.html","Serial Numbers","Serial numbers are used to uniquely identify components of HsM devices. A device can be uniquely identified by the serial number of one of its com...","./images/zoomimage.jpg"],
["./comm.html","Common","Following chapters describe aspects common to the whole HsM infrastructure.","./images/zoomimage.jpg"],
["./command-line-start.html","Running from command line","...exe --environemnt=dev","./images/zoomimage.jpg"],
["./command-message.html","Initiate Firmware Update","{     \"messageId\": \"a1baa49f-70dc-4266-b1e6-1a43707605456\",     \"recipientNetworkId\":\"142fe...","./images/zoomimage.jpg"],
["./command.html","Resource instances read message","{     \"messageId\": \"a1baa49f-70dc-4266-b1e6-1a4370760544\",     \"recipientNetworkId\":\"142fe2...","./images/zoomimage.jpg"],
["./comments_and_questions.html","Getting help","powered by Hagleitner ContentsContents Index Search ","./images/zoomimage.jpg"],
["./common.html","Common","Enter topic text here.",""],
["./component-types.html","Component types","Component types are used in device types to specify which kind of components can be used to fill a component placeholder. Besides the basic type o...","./images/zoomimage.jpg"],
["./compound-device-status.html","Compound device status","Compound member devices are part of the base set of devices to which device filters are applied, i.e. in the base set of devices to which the devi...",""],
["./compound-device-types.html","Compound device types","nh  HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are mo...","./images/zoomimage.jpg"],
["./compound-devices.html","Compound devices","The Digital Twin Service supports compound device types. It records the current relationship between devices and keeps a history of relationships ...","./images/zoomimage.jpg"],
["./configuration-app.html","Configuration app","Enter topic text here.",""],
["./configuration-files.html","Configuration files","{ \"Logging\": { \"NLog\": { \"IncludeScopes\": false, \"ParseMessageTemplates\": true, \"CaptureMessageProper...","./images/zoomimage.jpg"],
["./configuration-wlan.html","Configuration WLAN","To be able to configure the device the Gateway LAN provides a Wireless Configuration Network that can be used by to access the configuration API (...","./images/zoomimage.jpg"],
["./configuration-wlan2.html","Configuration for Ethernet","When configuring the gateway link to your local network via Ethernet plug the Ethernet cable into the WAN port at the back of the Gateway.","./images/zoomimage.jpg"],
["./configuration.html","Configuration","For running the Digital Twin Registration Agent a working directory and an environment name must be specified. The root working directory for all ...","./images/zoomimage.jpg"],
["./connection-topology.html","Connection topology","The Data Link Monitoring Service monitors which non-gateway devices are connected to which gateways and keeps a historical record for this informa...","./images/zoomimage.jpg"],
["./copyright_notice.html","Copyright notice","Copyright of this Reference Manual &#169; 2019-2021 Hagleitner. All rights reserved. &#60;%PRODUCTLINE%&#62; is a registered trademark or trademark of Ha...","./images/zoomimage.jpg"],
["./cuap-customer-selection-flow.html","Customer selection flow","Enter topic text here.","./images/zoomimage.jpg"],
["./cuapp-ble-advertising.html","Advertising","The Xibu App acts as BLE central and continuously discovers HsM BLE-networked devices. This includes processing of the data included in the advert...","./images/zoomimage.jpg"],
["./cuapp-ble-browsing.html","Browsing","The Xibu App continuously builds up connections to discovered HsM BLE-networked devices to read all resource instance values provided by these dev...","./images/zoomimage.jpg"],
["./cuapp-ble-communication.html","BLE communication","The Xibu App acts as BLE central for HsM devices. I.e. it discovers BLE-networked devices, processes advertisement packages of those devices and c...","./images/zoomimage.jpg"],
["./cuapp-debug-mode.html","Debug mode","For extended debugging the app can be switched to a debug mode. To do so go to the profile screen and tab on the e-mail address 5 times. After tha...","./images/zoomimage.jpg"],
["./cuapp-qrcode-screen.html","QR/Bar code scanner screen","The Xibu App can make use of QR-codes and barcodes to identify things, e.g. devices from QR-codes or customers form customer Bar-codes. For this t...","./images/zoomimage.jpg"],
["./cuapp.html","Xibu App","Enter topic text here.","./images/zoomimage.jpg"],
["./cumulated-offline-time.html","Total offline time","Whenever the Data Link Monitoring Service detects a change in the data link status from offline or temporarily offline to online it adds the time ...","./images/zoomimage.jpg"],
["./cumulated-online_-offline-time.html","Online ratio","The online ration is a key metric for the overall quality of the data link between a device and the HsM Backend. The online ratio is calculated as...","./images/zoomimage.jpg"],
["./customer-roles.html","Customer roles","Role XXX Assigned permission (with links to the permission topoic)","./images/zoomimage.jpg"],
["./customer.html","Customer","Filters for devices assigned to a given customer. Settings Setting Description Customer Only devices assigned to that customer will pass the filte...",""],
["./customers.html","Customer and Organizations","Relation type Description Invoicing Source customer receives the invoices for items delivered to the target customer Restricted by Navision to com...","./images/zoomimage.jpg"],
["./daan-time-series-analysis-request.html","Request","Time series analyses are based on time series analysis requests that give the Data Analysis Service what data to process and how to process that d...","./images/zoomimage.jpg"],
["./daan.html","Data Analysis Service","The HsM Data Analysis Service provides generic ways of analyzing the telemetry data produced by HsM devices. The Data Analysis Service is designed...","./images/zoomimage.jpg"],
["./dans-administrators-guide.html","Administrator&#39;s Guide","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./dans-internationalization.html","Internationalization","Language: Any textual input and output is in English (US)","./images/zoomimage.jpg"],
["./dans-internationalization_2.html","Internationalization","Language: Any textual input and output is in English (US)","./images/zoomimage.jpg"],
["./dans-single-value-analysis.html","Single value analysis","Single value analyses provide a generic way to analyze numeric resource instance data recorded by HsM. A single value analysis aggregates time ser...","./images/zoomimage.jpg"],
["./dans-time-series-analysis.html","Time Series analysis ","Time series analyses provide a generic way to analyze numeric resource instance data recorded by HsM. The time series analysis aggregates time ser...","./images/zoomimage.jpg"],
["./dans.html","Data Analysis Service","The HsM Data Analysis Service provides generic ways of analyzing the telemetry data produced by HsM devices. The Data Analysis Service is designed...","./images/zoomimage.jpg"],
["./dase.html","Data Analysis Service","Enter topic text here.","./images/zoomimage.jpg"],
["./data-analysis-service.html","Data Analysis Service","Enter topic text here.",""],
["./data-link-monitoring-protocol.html","Data link monitoring protocol","For reporting the status of non-gateway devices to the backend the stationary gateway shall use a simple protocol.",""],
["./data-link-monitoring-service-d.html","Data link monitoring service database","Data volume estimation Table: StationaryGatewayOnlineStatus 2E4 stationary gateways 100 bytes / record (rough estimation including page headers, i...",""],
["./data-link-monitoring-service-l.html","Data link monitoring service logic","The data link monitoring service records the result of monitoring data links between non-gateway devices and stationary gateways and the results o...",""],
["./data-link-monitoring-service.html","Data Link Monitoring Service","HsM stationary gateways are used to connect non-gateway devices to the HsM Backend permanently and therefore enable a near-real-time uplink commun...",""],
["./data-link.html","Data link","The HsM system can also manage pure analog dispensers (with no data link to the HsM Backend), this device filter term type can be used to filter d...",""],
["./data-loss-protection.html","Data loss protection","HsM takes many precautions to prevent data loss and to be able to recover the system without data loss after hardware failures, malware attacks or...","./images/zoomimage.jpg"],
["./data-loss-protection_2.html","Data loss protection","Blob storage Client Service Database","./images/zoomimage.jpg"],
["./data-series-source.html","Processing","The time series analysis will process data based on the logic sketched in figure 3.","./images/zoomimage.jpg"],
["./data-series-source_2.html","Processing","The time series analysis will process data based on the logic sketched in figure 3. ","./images/zoomimage.jpg"],
["./data-source.html","Data source","The data source defines what system created a record in the TRACE_Product table. Usually Records in the TRACE_Product Table should be created by t...","./images/zoomimage.jpg"],
["./date-interval-definition.html","Date interval definitions","Date intervals are used to filter or query timestamped data that is within an given start date and end date. Since HsM deals with time-series a lo...",""],
["./date-interval.html","Date interval specification","Date intervals are used to filter or query timestamped data that is within an given start date and end date. Since HsM deals with time-series a lo...",""],
["./date-time-handling.html","Date time handling","The Data Analysis Service works totally in UTC. I.e. the API expects all date time parameters to be in UTC and all responses including date time v...","./images/zoomimage.jpg"],
["./date-time-offset.html","Date time offset","HsM is designed to work consistently and comprehensible in different time-zones. To achieve this HsM usually stores date-time values as date-time-...","./images/zoomimage.jpg"],
["./debug-mode.html","Debug mode","For extended debugging the app can be switched to a debug mode. To do so go to the profile screen and tab on the e-mail address 5 times. After tha...","./images/zoomimage.jpg"],
["./decision.html","Detect version of a &#60;%SYSTEMNAME%&#62; serial number","If length is exactly 13",""],
["./definitions.html","Definitions","device type: component type compound device type compound component",""],
["./delivering-device-types-via-th.html","Delivering device types via the browse API","When device types are requested and then delivered via the browse API their component type placeholders are resolved to component types, the accor...","./images/zoomimage.jpg"],
["./delivery-note.html","Delivery note","C2DD issues delivery notes if a message delivery request has reached a final state. Final states can be: ","./images/zoomimage.jpg"],
["./device-dates.html","Installation date","Filters for devices based on their installation date, i.e. the date when the device was installed at a specific locaiton.",""],
["./device-dates_2.html","Birth date","Filters by birth date of the device (or to be exact by the birth date of the digital twin).",""],
["./device-filter-term-types.html","Device filter term types","Device filter term types are predefined building blocks for device filters. Term types can have settings and have their own validation rules.",""],
["./device-filter.html","Device filter","A device filter is a logical expression that can be applied to the devices managed by the HsM Client Service to filter for a subset of these devic...",""],
["./device-gateway-link-status.html","Device gateway link status","Application Properties Property  message-type Always set to device-gateway-link-status message-type-version 1.0.0  sender EUI48 or EUI64...","./images/zoomimage.jpg"],
["./device-list.html","Device list","The blue circle is used to install a device and calls the device identification screen","./images/zoomimage.jpg"],
["./device-provisioning-registrati.html","Device Provisioning Registration Agent","Flow:  * Start process every X hours at timestamp t * Get all stationary gateway devices from Provider DB, born after t - X - delta   De...","./images/zoomimage.jpg"],
["./device-provisioning-service.html","Device Provisioning Service","HsM uses an Azure Device Provisioning service for Stationary gateways so that these gateways will initially connect to the right HsM OeM Partner&#39;s...",""],
["./device-qr-codes.html","HsMDevice QR Codes","All devices managed by the HsM have stickers with a QR code that carries information about the device. This QR code sticker can be used by clients...",""],
["./device-type-groups.html","Device type groups","Device type groups are global catalog elements that are used to group Device types by specific characteristics. This allows clients of HsM to hand...","./images/zoomimage.jpg"],
["./device-type.html","Device type","Filters for devices that are of one of the given device types.",""],
["./device-type2.html","Device type","A device type is the scheme that defines the logical and physical structure of HsM device. This includes the components that are used for instance...",""],
["./device-with-network-interface(.html","Device with network interface(50-05)","Additional to the content parts described in Device QR Codes this content type also includes an EUI-48 network Id. This content type is used for d...","./images/zoomimage.jpg"],
["./digital-birth.html","On Premise infrastructure","Enter topic text here.",""],
["./digital-twin-lifecycle-status.html","Digital Twin lifecycle","In HsM every digital twin has a defined life cycle state at all times. The Digital Twin Service keeps track of the life cycle state of devices and...",""],
["./digital-twin-registration-agen.html","Digital Twin Registration Agent","Enter topic text here.",""],
["./digital-twin-service.html","Digital Twin Service","The HsM Digital Twin Service is part of the 5:57 PM neutral backend. It is the place where digital twins for each produced HsM device are initiall...",""],
["./disclaimer.html","Disclaimer","Due to continued product development, information in this Reference Manual can change without notice.  ","./images/zoomimage.jpg"],
["./display-groups.html","Display Groups","The display groups defined with a firmware variant version are a partition of the set of resource instances defined with that firmware variant ver...","./images/zoomimage.jpg"],
["./display-groups2.html","Resource instance compositions","While display groups defined with a firmware variant version give clients a hint how to visualize the set of resource instances within that firmwa...","./images/zoomimage.jpg"],
["./dlms-capabilities.html","Detection capabilities","How quickly the Data Link Monitoring Service detects changed data-link states depends on many different things among them the configuration of the...","./images/zoomimage.jpg"],
["./dlms-capability.html","Configuration &#38; Capabilities","Enter topic text here.","./images/zoomimage.jpg"],
["./dlms-configuration.html","Configuration options","Gateway Heartbeat message interval:  Default = 1h Valid value range: 15 min - 72h Full device gateway connection information send interval: 6...","./images/zoomimage.jpg"],
["./dlms-connection-metrics.html","Connection metrics","The results of monitoring the data-links between BLE-networked devices and monitoring the data-links between stationary gateways and the the HsM B...","./images/zoomimage.jpg"],
["./dlms-connection-topology.html","Connection topology","The Data Link Monitoring Service monitors which BLE-networked devices are connected to which stationary gateways and keeps a historical record of ...","./images/zoomimage.jpg"],
["./dlms-data-link-monitoring-gateway-backend.html","Data link between stationary gateways and the HsM backend","The Data Link Monitoring Service monitors the data link between stationary gateways and the HsM Backend. ","./images/zoomimage.jpg"],
["./dlms-data-link-monitoring-logic.html","Processing of monitoring results","The Data Link Monitoring Service records the result of monitoring data-links between BLE-networked devices and stationary gateways and the results...","./images/zoomimage.jpg"],
["./dlms-data-link-monitoring-nongateway-gateway.html","Data link between non-gateway devices and stationary gateways","Gateways actively monitor the Bluetooth communication links with non-gateway devices and report the status of this links to the Data link monitori...","./images/zoomimage.jpg"],
["./dlms-data-link-status-ble-networked.html","BLE-networked devices","The data-link between a BLE-networked device and the HsM Backend via stationary gateways is evaluated by the Data Link Monitoring Service into a d...","./images/zoomimage.jpg"],
["./dlms-data-link-status-expectation.html","Expectation","Enter topic text here.","./images/zoomimage.jpg"],
["./dlms-data-link-status-gateways.html","Stationary gatways","The data-link between a gateway device and the HsM Backend is evaluated by the Data Link Monitoring Service into following states listed in table 30","./images/zoomimage.jpg"],
["./dlms-data-link-status.html","Data-link status","The data-link status describes connection of devices with the HsM Backend based on the actual physical connection state (online, offline), the exp...","./images/zoomimage.jpg"],
["./dlms-generated-resource-instance-values.html","Generated resource instance values","The Data Link Monitoring Service forwards key metrics as resource instance values. I.e. the Data Link Monitoring Service calculates these metrics ...","./images/zoomimage.jpg"],
["./dlms-metrics-online-ratio.html","Online ratio","The online ration is a key metric for the overall quality of the data-link between a device and the HsM Backend. The online ratio is calculated fr...","./images/zoomimage.jpg"],
["./dlms-metrics-total-offline-time.html","Total offline time","Whenever the Data Link Monitoring Service detects a change in the data-link status from offline or temporarily offline to online it adds the time ...","./images/zoomimage.jpg"],
["./dlms-metrics-total-online-time.html","Total online % offline time","Whenever the Data Link Monitoring Service detects a change in the data-link status from online to offline, temporarily offline or not connected it...","./images/zoomimage.jpg"],
["./dlms-monitoring-gateway-devices.html","Monitoring stationary gateway devices","The Data Link Monitoring Service monitors the data-link between stationary gateways and the HsM Backend based on heartbeat messages sent by statio...","./images/zoomimage.jpg"],
["./dlms-monitoring-nongateway-devices.html","Monitoring BLE-networked devices","Stationary gateways actively monitor the BLE communication links with BLE-networked devices and report the status of these links (online or offlin...","./images/zoomimage.jpg"],
["./dlms-presented-status-gateway-devices.html","Stationary gatways","The data-link between a gateway device and the HsM Backend is evaluated by the Data Link Monitoring Service into following states listed in table 21","./images/zoomimage.jpg"],
["./dlms-presented-status-non-gateway-devices.html","BLE-networked devices","The data-link between a BLE-networked device and the HsM Backend via stationary gateways is evaluated by the Data Link Monitoring Service into the...","./images/zoomimage.jpg"],
["./dlms-presented-status.html","Data link status","The data link status describes the connection state between non-gateway devices and the HsM Backend and gateway devices and the HsM Backend. The d...","./images/zoomimage.jpg"],
["./dlms-recording-of-data-link-status.html","Virtual Resource Instances written","The Data Link Monitoring Service records key metrics of its monitoring activity as resource instance values. This way those key metrics are made a...","./images/zoomimage.jpg"],
["./dlms-resource-instances-written.html","Metrics forwarded as resource instance values","The Data Link Monitoring Service forwards key metrics as resource instance values. I.e. the Data Link Monitoring Service calculates these metrics ...","./images/zoomimage.jpg"],
["./dlms-rest-api.html","REST API","Terminiology DataLinkConenctionState: Inludes Status, ComputedAt, ComponentId, OnlineTime, OfflineTime DeviceStateResponse: Online/Offline Logged ...","./images/zoomimage.jpg"],
["./dlms.html","Data Link Monitoring Service","HsM stationary gateways are used to connect BLE-networked devices to the HsM Backend permanently and therefore enable a near-real-time up-link com...","./images/zoomimage.jpg"],
["./dlse.html","Data Link Monitoring Service","HsM stationary gateways are used to connect non-gateway devices to the HsM Backend permanently and therefore enable a near-real-time uplink commun...",""],
["./dpse.html","Device Provisioning Service","HsM uses an Azure Device Provisioning service for Stationary gateways so that these gateways will initially connect to the right HsM OeM Partner&#39;s...","./images/zoomimage.jpg"],
["./dtra-installation.html","Installation","Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET Core 3.1 run tim...","./images/zoomimage.jpg"],
["./dtra-operations-guide.html","Operations guide","The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debugging and testing purpos...","./images/zoomimage.jpg"],
["./dtra-queuing.html","Queuing","Enter topic text here.","./images/zoomimage.jpg"],
["./dtra.html","Digital Twin Registration Agent","Enter topic text here.","./images/zoomimage.jpg"],
["./dtws-lifecycle-compound.html","Lifecycle states transitions for compound devices","For compound devices the Digital Twin Service enforces a consistent life-cycle states. I.e. Compound parent and compound member always have to be ...","./images/zoomimage.jpg"],
["./dtws-lifecycle-states.html","Lifecycle states and transitions","Status   Allows transition to Produced Device was produced and is registered for a specific HsM OEM Partner. This state is the initial state ...","./images/zoomimage.jpg"],
["./dtws-lifecycle.html","Digital Twin lifecycle","In HsM every digital twin has a defined life cycle state at all times. The Digital Twin Service keeps track of the life cycle state of devices and...","./images/zoomimage.jpg"],
["./dtws-operations-guide.html","Operations Guide","Enter topic text here.","./images/zoomimage.jpg"],
["./dtws.html","Digital Twin Service","The HsM Digital Twin Service is part of the HsM neutral backend. It is the place where digital twins for each produced HsM device are initially re...","./images/zoomimage.jpg"],
["./enumerating-resource-instances.html","Enumerating resource instances","Since compound device types can contain multiple compound member device types, they can also contain multiple firmware types. Therefore the possib...","./images/zoomimage.jpg"],
["./environment-setting.html","Environment setting","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./environment-variable-dtra_conf.html","Environment variable DTRA_CONFIG_DIR","The Windows System Environment Variable DTRA_CONFIG_DIR defines the directory where configuration files are expected and where the Digital Twin Re...","./images/zoomimage.jpg"],
["./eui-(extended-unique-identifie.html","EUI (Extended Unique Identifier)","In HsM EUIs (Extended Unique Identifiers) are used frequently for identification of devices. There are two different EUI types. EUI-48: A 48 bit E...","./images/zoomimage.jpg"],
["./eventual-consistency.html","Eventual consistency","Data Link monitoring Service The C2DD gets topology information from the DLMS and will  Changes to the topology will be propagated by the DLM...","./images/zoomimage.jpg"],
["./example_topic.html","%Text%","Each topic begins with a short introduction or abstract that describes the contents of the topics. This topic is an example topic that shows all s...","./images/zoomimage.jpg"],
["./execution-scope.html","Execution Scope","When a device filter is executed, it is always executed in a specific scope. This execution scope defines the base set of devices to which the fil...",""],
["./expectation.html","Expectation","If a device is not connected to the HsM Backend this can be either an error or it can be an expected state. Therefore the data-link status of of a...","./images/zoomimage.jpg"],
["./extended-properties.html","Extended Properties","The Catalog Service can define extended properties for each device type. The Digital Twin Service is the place where the values for these extended...","./images/zoomimage.jpg"],
["./extended-properties2.html","Extended Properties","Each device type can have definitions for extended properties. Extended properties are properties of devices that are instances extended property ...","./images/zoomimage.jpg"],
["./frontends.html","Frontends","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./func-iot-routing-rvs.html","Func-iot-routing-rvs","Enter topic text here.","./images/zoomimage.jpg"],
["./functions.html","Functions","HsM uses Azure IoT functions for processing IoT-Hub messages and forwarding them to storage services.","./images/zoomimage.jpg"],
["./gateway-configuration.html","Gateway configuration","Enter topic text here.","./images/zoomimage.jpg"],
["./gateway-devices.html","Gateway devices","In HsM gateways are also handled as HsM devices and have their own data-link status.",""],
["./gateway-heartbeat.html","Gateway heartbeat","The Gateway Heartbeat message type is used by stationary gateways to actively inform the HsM Backend about it&#39;s alive status. These I-am-alive-sig...","./images/zoomimage.jpg"],
["./gateway-oriented-storage-struc.html","Gateway oriented storage structure","The gateway oriented blob storage container is not turned on by default but can be enabled by configuration of the Func-iot-routing-rvs function. ...","./images/zoomimage.jpg"],
["./gateway-registration.html","Gateway registration","All gateways must be registered with the Azure IoT Hub before they can send messages.","./images/zoomimage.jpg"],
["./global-roles.html","Global roles","Enter topic text here.","./images/zoomimage.jpg"],
["./glossary.html","Glossary","BLE Bluetooth Low Energy. Wireless personal area network technology. BLE-networked device HsM devices that send or receive data via BLE. BLE-netwo...","./images/zoomimage.jpg"],
["./handling-of-compound-devices.html","Handling of compound devices","If a devices that matches the filter has member devices or is a member device then the Parent or Children are also delivered in the result set.",""],
["./handling-of-invalid-device-filters.html","Validity constraints","Several constraints must be fulfilled for a device filter to be called valid. This includes constraints that apply to the structure of the express...",""],
["./hsm-gateway-lan.html","HsM Gateway LAN","The HsM Gateway LAN is a BLE (Bluetooth Low Energy) Gateway that connects BLE-networked devices to your local network and eventually to the HsM Hs...","./images/zoomimage.jpg"],
["./hsm-oem-customers.html","HsM OEM Customers","Entities in the Catalog Service are mapped to one or more OEM Customers. E.g. a device type is mapped to one or more OEM-Customers.","./images/zoomimage.jpg"],
["./hsm-qr-codes.html","Device QR codes","All devices managed by HsM have QR codes that carry information about the device. The data encoded in these QR codes is used by clients (like Apps...","./images/zoomimage.jpg"],
["./hsmd-ble-advertising.html","Advertising","HsM BLE-networked devices send out advertising packages notify other BLE devices (including HsM gateway devices about their existence. The adverti...","./images/zoomimage.jpg"],
["./hsmd-ble-ceacons.html","Beacons","The operating systems of mobile devices (smart phones) can detect when they enter or exit a particular setting by monitoring BLE beacons. BLE beac...","./images/zoomimage.jpg"],
["./hsmd-ble-communication.html","BLE Communication","HsM BLE-networked devices can communicate with BLE centrals (Xibu App, HsM stationary gateways). This communication is used for a local interactio...","./images/zoomimage.jpg"],
["./hsmd.html","HsM devices","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./hybrid-(50-02).html","Hybrid (50-02)","Additional to the content parts described in Device QR Codes this content type also includes an EUI64 (BLUUID) network ID. This content type is us...","./images/zoomimage.jpg"],
["./identifying-a-device.html","Identifying a device","To add a device, tap on the blue circle with the camera symbol in the bottom right corner of the screen. The circle will only appear when the Disp...","./images/zoomimage.jpg"],
["./impr-blob-contents.html","Blob contents","All blobs written in the raw data storage are JSON documents. They include the IoT Hub message properties as well as the original message body.","./images/zoomimage.jpg"],
["./impr-blobstorage-structure.html","Blob storage structure","Azure Blob storage is a cheap storage space that can hold a nearly unlimited amount of data, however it is not a database that can be used to exte...","./images/zoomimage.jpg"],
["./impr-data-processing-functions.html","Data processing functions","HsM uses Azure functions to process the messages received by the IoT Hub and to route these messages to various storage systems. (see Message rout...","./images/zoomimage.jpg"],
["./impr-func-iot-routing-rvs.html","func-iot-routing-rvs","This function persists the IoT messages to the Raw Data Storage. It builds up the raw data storage structure and creates a JSON document including...","./images/zoomimage.jpg"],
["./impr-gateway-registration.html","Gateway registration","All gateways must be registered with the Azure IoT Hub before they can send messages.","./images/zoomimage.jpg"],
["./impr-iot-routing-css.html","func-iot-routing-css","This function persists the latest value of resource instances to the current status storage table within the database of the Client Service. This ...","./images/zoomimage.jpg"],
["./impr-iot-routing-legacy.html","func-iot-routing-legacy","All messages that did not match the filter criteria of any route fill be caught by the built in Azure IoT Hub endpoint and will be routed to this ...","./images/zoomimage.jpg"],
["./impr-iot-routing-tss.html","func-iot-routing-tss","This function persists the values extracted from resource instance data messages to the time series database which is the basis for the data analy...","./images/zoomimage.jpg"],
["./impr-message-routing.html","Message routing","HsM uses Azure infrastructure to route messages received at the IoT Hub to services for further processing and storage. Figure 8 shows an overview...","./images/zoomimage.jpg"],
["./impr-message-types.html","Message types","HsM uses different message types for communication via Azure IoT Hub. Table 37 provides an overview of all used message types. ","./images/zoomimage.jpg"],
["./impr-messagetype-c2dd-delivery.html","Gateway process confirmation","This message type is used by gateway devices to indicate the result of a process started via the C2D Message Delivery Service","./images/zoomimage.jpg"],
["./impr-messagetype-device-gateway-connection-status.html","Device-gateway connection status","The device-gateway connection status message type is used by stationary gateways to actively inform the HsM Backend about connections between the ...","./images/zoomimage.jpg"],
["./impr-messagetype-gateway-heartbeat.html","Gateway heartbeat","The Gateway Heartbeat message type is used by stationary gateways to actively inform the HsM Backend about it&#39;s alive status. These I-am-alive-sig...","./images/zoomimage.jpg"],
["./impr-messagetype-resource-instance-data.html","Resource instance data","The Resource instance data message type is to transfer the values of resources instances in HsM devices to the HsM Backend. ","./images/zoomimage.jpg"],
["./impr-raw-data-storage.html","Raw data storage","The Raw Data Storage is an Azure Blob Storage that keeps copies of the original HsM messages received by the IoT Hub. The purpose of the raw data ...","./images/zoomimage.jpg"],
["./impr.html","IoT Message Processing","HsM uses Azure IoT infrastructure for device-to-cloud and cloud-to-device communication. I.e. data produced by HsM devices is delivered to the HsM...","./images/zoomimage.jpg"],
["./index.html","Preface","This Reference Manual describes the Hagleitner Sense Management system (HsM). It covers all aspects of HsM. It includes information for the occasi...","./images/zoomimage.jpg"],
["./installation.html","Installation","Prerequisites .NET Core 3.1 runtime: The Digital Twin Registration Agent is a .NET Core 3.1.10 application and therefore the .NET Core 3.1 run tim...",""],
["./installing-a-device.html","Installing a device","The Xibu App can be used to install devices. The serial number needed to install devices can be given by scanning the QR-Code on the device or by ...","./images/zoomimage.jpg"],
["./intended_audience.html","Intended audience","This Reference Manual covers all aspects of HsM. It includes information for the occasional system user, power users, administrators but also for ...","./images/zoomimage.jpg"],
["./inter-service-communication.html","Inter Service Communication","Enter topic text here.","./images/zoomimage.jpg"],
["./internationalization.html","Internationalization","We use date time offset.","./images/zoomimage.jpg"],
["./introduction.html","Introduction","powered by Hagleitner ContentsContents Index Search ","./images/zoomimage.jpg"],
["./introduction2.html","Introduction","HsM supports the concept of compound devices, i.e. devices can include other devices. These devices within other devices, however, are more than j...","./images/zoomimage.jpg"],
["./isco.html","Inter Service Communication Service","The inter service communication service is implemented as Azure Service Bus. It is used to provide decoupled communication paths between services ...","./images/zoomimage.jpg"],
["./key-metrics-available-through-.html","REST API","Any device PUT /device/{id}/statistic-reset :Will reset statistical values stored for this device (online-ratio, time-sums etc) GET /device/{id}/d...","./images/zoomimage.jpg"],
["./latest-status-update.html","Latest status update","Filters for devices that sent a resource instance value (for any resource instance) within the configured time span.",""],
["./leds.html","LEDs","The Gateway has 3 LEDs that indicate the current status of the Gateway and its network connections.","./images/zoomimage.jpg"],
["./life-cycle-status.html","Life cycle status","Enter topic text here.",""],
["./lifecycle-state.html","Lifecycle state","The lifecycle state represents the actual lifecycle state of a catalog element. It can be used to restrict access of elements to a certain group o...","./images/zoomimage.jpg"],
["./location-of-configuration-file.html","Location of configuration file","All  configuration for Digital Twin Registration Agent is done through a configuration file. ","./images/zoomimage.jpg"],
["./location-tree-filter.html","Location tree filter","Filters for devices that are installed at specific locations with in the location tree of customers.",""],
["./locking.html","Locking","For some operations on customer data in HSM the customer needs to be locked, so that no data inconsistencies can occur. This is mostly caused by t...","./images/zoomimage.jpg"],
["./logging.html","Logging","For monitoring the Digital Twin Registration Agent the program logs via the nlog framework and therefore allows for versatile routing of log messa...","./images/zoomimage.jpg"],
["./logging2.html","Logging","Enter topic text here.","./images/zoomimage.jpg"],
["./logical-operators.html","Logical operators","Device filters support following logical operators:",""],
["./manual-identification.html","Manual identification","After pressing the blue circle, the manual identification screen will open. Here are two fields for entering the device information:","./images/zoomimage.jpg"],
["./manually-updating-firmware.html","Manually updating Firmware","Note: The gateway has an automated procedure to update its firmware. Manual updating is for professionals only.","./images/zoomimage.jpg"],
["./message-delivery-process.html","Message delivery process","Message delivery trys retry * Pass in delegate * Delegate successfully executed -&#62; message completed * Delegate not successful (exception) -&#38;gt...","./images/zoomimage.jpg"],
["./message-types.html","Message types","C2DD accepts different types of messages.","./images/zoomimage.jpg"],
["./metrics.html","Connection metrics","The results of monitoring the data links between non-gateway devices, gateways and the HsM Backend are processed by the Data Link Monitoring Servi...","./images/zoomimage.jpg"],
["./mobile-gateway.html","Mobile gateway","The app acts as a mobile gateway for BLE-networked devices, i.e. it relays data to/from the HsM Backend. ","./images/zoomimage.jpg"],
["./monitoring-data-link-between-n.html","Monitoring data link between non-gateway devices and stationary gateways","Gateways actively monitor the Bluetooth communication links with non-gateway devices and report the status of this links to the Data link monitori...",""],
["./monitoring-data-link-between-s.html","Monitoring data link between stationary gateways and the HsM backend","The Data link monitoring service monitors the data link between stationary gateways and the HsM Backend. The technical environment allows to immed...",""],
["./neutral-backend-infrastructure.html","Neutral backend infrastructure","HsM is designed to be operated by different HsM OEM Partners, I.e. different OEM Partner can host their own HsM infrastructure and can therefore o...","./images/zoomimage.jpg"],
["./new-topic.html","New topic","Enter topic text here.","./images/zoomimage.jpg"],
["./non-gateway-devices.html","Non gateway devices","The data-link between a non-gateway device and the HsM Backend via gateways can be in one of the following states:",""],
["./on-premise-infrastructure.html","On premise infrastructure","Step 1: Scan QR Code Gateway wird wie jedes HsM Gerät hinzugefügt. Gateway ist nicht konfiguriert TODO: iOS Zuletzt entdeckt am muss weg TODO: Ask...","./images/zoomimage.jpg"],
["./operations-guide.html","Operations Guide","Enter topic text here.",""],
["./operations-guide2.html","Operations guide","Enter topic text here.",""],
["./operations-guide3.html","Operations guide","Enter topic text here.",""],
["./operations-guide4.html","Operations guide","The Digital Twin Registration Agent is a Windows program that is intended to be run as a Windows Service but can (for debugging and testing purpos...",""],
["./operations.html","Operations","Enter topic text here.","./images/zoomimage.jpg"],
["./operations2.html","Service-level","The following chapters define the quality, availability of the services HsM offers. It therefore defines what the client/user of the HsM services ...","./images/zoomimage.jpg"],
["./operations2_2.html","Service-level","The following chapters define the quality, availability of the services Client Service offers. It therefore defines what clients/users of the Clie...","./images/zoomimage.jpg"],
["./organization-roles.html","Organization roles","Enter topic text here.","./images/zoomimage.jpg"],
["./organization.html","Organization","Filters for devices assigned to customers within an given organization.",""],
["./pdpr.html","Primary Data Processing","HsM uses Azure IoT infrastructure for device-to-cloud and cloud-to-device communication. I.e. data produced by HsM devices is delivered to the HsM...","./images/zoomimage.jpg"],
["./permissions.html","Permissions","Table 5 lists all permissions defined in HsM. Permissions are identified by a permission code.","./images/zoomimage.jpg"],
["./placeholder-visibility.html","Placeholder visibility","Component placeholders are marked with an visibility attribute. This attribute is a hint to software products showing either the device type&#39;s com...","./images/zoomimage.jpg"],
["./prdb-func-iot-routing-rvs.html","Func-iot-routing-rvs","Validation Resource instance values with a time stamp that is smaller than now - 30d will be disregarded Resource instance values with a time stam...","./images/zoomimage.jpg"],
["./prdb-gateway-registration.html","Gateway registration","All gateways must be registered with the Azure IoT Hub before they can send messages.","./images/zoomimage.jpg"],
["./prdp-data-processing-functions.html","Primary data processing functions","Besides the Data Link Monitoring Service HsM uses Azure functions to process the messages received by the IoT Hub and to route the data in those m...","./images/zoomimage.jpg"],
["./prdp-message-routing.html","Message routing","HsM uses Azure infrastructure to route messages received at the IoT Hub to services for further processing and storage. Figure 6 shows an overview...","./images/zoomimage.jpg"],
["./prdp-message-types.html","Message types","HsM uses different message types for communication via Azure IoT Hub. Table 37 provides an overview of all used message types. ","./images/zoomimage.jpg"],
["./prdp-messagetype-device-gateway-connection-status.html","Device-gateway connection status","The device-gateway connection status message type is used by stationary gateways to actively inform the HsM Backend about connections between the ...","./images/zoomimage.jpg"],
["./prdp-messagetype-gateway-heartbeat.html","Gateway heartbeat","The Gateway Heartbeat message type is used by stationary gateways to actively inform the HsM Backend about it&#39;s alive status. These I-am-alive-sig...","./images/zoomimage.jpg"],
["./prdp-messagetype-resource-instance-data.html","Resource instance data","Application Properties Property Description message-type resource-instance-data message-type-version 1.0.0  sender-id EUI48 or EUI64 of the g...","./images/zoomimage.jpg"],
["./prdp-raw-data-storage-date-oriented.html","Date oriented storage structure","The date oriented blob storage container is the place where HsM keeps a copy of all incoming IoT Hub messages. HsM does not use or process the dat...","./images/zoomimage.jpg"],
["./prdp-raw-data-storage-gateway-oriented.html","Gateway oriented storage structure","The gateway oriented blob storage container is not turned on by default but can be enabled by configuration of the Func-iot-routing-rvs function. ...","./images/zoomimage.jpg"],
["./prdp-raw-data-storage.html","Raw data storage","The raw data storage is an Azure Blob Storage that keeps a copy the original HsM IoT Hub messages for long term data safety. ","./images/zoomimage.jpg"],
["./predefined-adaptive-date-inter.html","Predefined adaptive date intervals","For easier definition of adaptive date intervals the HsM Client Service provides some predefined date intervals",""],
["./presented-data-link-status.html","Data link status","Please enable JavaScript to view this site. ",""],
["./primary-data-processing-functi.html","Primary data processing functions","HsM uses Azure functions to persist data received through the Azure IoT-hub to various storage systems.","./images/zoomimage.jpg"],
["./primary-data-processing.html","Primary Data Processing","HsM uses Azure IoT Hub infrastructure for device-to-cloud and cloud-to-device communication.",""],
["./problem-types.html","Problem types","Enter topic text here.","./images/zoomimage.jpg"],
["./product-record-state.html","TRACE_ProductRecordState","Records in the ProductRecordState table define available product record states. Product Record sates define the status of a product from the viewp...","./images/zoomimage.jpg"],
["./product-type-code.html","Product type code","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./provieder-db.html","Provider DB","The provider DB is the place where the first digital representation of HsM devices is stored. The End-Test procedure writes data records to tables...","./images/zoomimage.jpg"],
["./quantity-structure.html","Quantity structure","HsM is designed as a single system for all data of an HsM OEM Partner, i.e. all the data that is recorded and managed for all customers and organi...","./images/zoomimage.jpg"],
["./quantity-structure_2.html","Quantity structure","Entity  Customers 1E6 Contacts  2E6 Organizations 200 Devices 1E6","./images/zoomimage.jpg"],
["./queue.html","Queue","The queue subdirectory is used as a queue for devices that need to be registered with the Digital Twin Service. The queue directory is filled by q...","./images/zoomimage.jpg"],
["./queuing-and-retry.html","Queuing and retry","When clients commission the Cloud To Device Distribution Service with a task the Cloud To Device Distribution Service will first persist this task...","./images/zoomimage.jpg"],
["./queuing.html","Queuing","Enter topic text here.",""],
["./raw-data-blob-storage-structur.html","Date oriented storage structure","The date oriented blob storage container is the place where HsM keeps a copy of all incoming IoT Hub messages. HsM does not use or process the dat...","./images/zoomimage.jpg"],
["./raw-value-analysis.html","Raw value analysis","Raw value analyses provide a generic way to fetch any resource instance data recorded by HsM. Requests can be done only for one device at a time a...","./images/zoomimage.jpg"],
["./raw-value-time-series.html","Raw value time series","Raw value analyses provide a generic way to fetch any resource instance data recorded by HsM. Requests can be done only for one device at a time a...","./images/zoomimage.jpg"],
["./reacting-to-topology-changes.html","Reacting to topology changes","Changes to the topology - i.e which BLE-networked device is connected to the HsM Backend via which gateway device - will be propagated by the Data...","./images/zoomimage.jpg"],
["./recording-of-data-link-status.html","Recording of data link status","The data link status of HsM Backend devices (non-gateway as well as gateway devices) is recorded as virtual resource instance values for each devi...",""],
["./removing-a-windows-service.html","Removing a Windows Service","Using PowerShell Note you need to run PowerShell with administrative privileges to modify Windows Services. Removing a Windows Service for the Dig...","./images/zoomimage.jpg"],
["./reset-button.html","Reset button","Press time Action &#60; 1s Reboot device &#62;= 2 and &#60; 6 seconds (fast flashing power LED) Toggle WLAN AP on/off &#62;= 8 to &#60;= 15 s (slow fla...","./images/zoomimage.jpg"],
["./resource-equivalent-latest-val.html","Resource equivalent latest value","Enter topic text here.",""],
["./resource-instance-changes.html","Resource Instances write message","{     \"messageId\": \"a1baa49f-70dc-4266-b1e6-1a4370760544\",     \"recipientNetworkId\":\"142fe2...","./images/zoomimage.jpg"],
["./resource-instance-equivalents.html","Resource instance equivalents","Resource instance equivalents are global catalog elements that are used to link resource instances with the same meaning accross different  d...",""],
["./resource-instance-ids.html","Resources and resource instances","For virtual and transformed resource instances we can use the following range of resource type IDs. ","./images/zoomimage.jpg"],
["./resource-instance-value2.html","Latest Resource instance value","Filters devices by their latest reported resource instance values. ",""],
["./rest-api.html","REST API","The REST API documentation of the HsM Catalog Service can be found at http://catalog.hsm.digital/swagger/index.html.","./images/zoomimage.jpg"],
["./rest.html","REST","Creating &#38; modifying tasks POST c2dd/tasks: Create a new task: ?how do we handle different types of messages here?, returns message ID (create...","./images/zoomimage.jpg"],
["./result-message.html","Result message","{     \"messageId\": \"a1baa49f-70dc-4266-b1e6-1a4370760544\",     \"status\":\"Success &#124; Failure&#38;...","./images/zoomimage.jpg"],
["./result.html","result","Single value Acutally evaluated timespan Number of values aggregated","./images/zoomimage.jpg"],
["./roles.html","Roles","Table 6 lists the roles defined in HsM, table 7 shows the permissions assigned to each role.","./images/zoomimage.jpg"],
["./run-as-windows-service.html","Creating a Windows Service","While there are many ways to register a program as a Windows Service, we recommend the following approach with PowerShell. Note you need to run Po...","./images/zoomimage.jpg"],
["./schedule.html","Schedule","Technical checks should be performed regularly. A customer is therefore assigned to a technical check schedule that defines how often a technical ...","./images/zoomimage.jpg"],
["./scope-availability-.html","Scope Availability ","Help for the UI",""],
["./seap.html","Service App","Enter topic text here.","./images/zoomimage.jpg"],
["./sensor-data-.html","Resource Instance data","System Properties Property  content-type application/json  content-encoding utf-8  Application Properties Property  message-ty...","./images/zoomimage.jpg"],
["./serial-numbers.html","Serial Numbers","Serial numbers are used to uniquely identify components of HsM devices. A device can be uniquely identified by the serial number of one of its com...",""],
["./service-app.html","Service App","Enter topic text here.",""],
["./service-dependencies-and-resi2.html","Service dependencies and resilience","Blob Storage Logging Storage Client Service Database App Service  Catalog Service The client service needs information from the catalog servi...","./images/zoomimage.jpg"],
["./service-dependencies-and-resil.html","Service dependencies and resilience","Data Link Monitoring Service The C2DD needs the DLMS to determine which stationary gateways it shall use to deliver messages to devices. If the DL...","./images/zoomimage.jpg"],
["./service-level.html","Availability","Generally HsM aims at a 24/7/365 availability. For technical reasons it is however not possible to provide 100% availability and therefore the ava...","./images/zoomimage.jpg"],
["./service-level_2.html","Availability","The Client Service is aimed at 99.59% availability. Being the single entry point for user interfaces the client service defines the availability o...","./images/zoomimage.jpg"],
["./single-value-analysis-request.html","Request","Single value analysis are based on single value analysis requests that provide the Data Analysis Service with information what data to process and...","./images/zoomimage.jpg"],
["./sla.html","SLA","Availability C2DD promises a general availability of 99.2% with a maximum continuous downtime of 4 h. I.e. a total of 72 hours downtime per year. ...","./images/zoomimage.jpg"],
["./starting-and-stopping-the-wind.html","Running as Windows service","Enter topic text here.","./images/zoomimage.jpg"],
["./static-date-interval-definition.html","Static date interval definition","A static date interval definitions are specified by a fixed lower boundary and upper boundary.",""],
["./static-date-interval-specifica.html","Static date interval specification","A static date interval specification contain a fixed lower and upper boundary.",""],
["./status_of_topics.html","Status of topics","We use the status of the topics to define the working status and the releas status","./images/zoomimage.jpg"],
["./support.html","Support","HsM is powered by Hagleitner . &#169; 2021. ContentsContents Index Search ","./images/zoomimage.jpg"],
["./technical-check.html","Technical Check","Definition of overdue The technical checks for a customer has a due date d The technical check for a customer has a grace period before g1, and gr...","./images/zoomimage.jpg"],
["./term-type-availability.html","Term type availability","Some device filter terms are restricted to HsM users with specific permissions.",""],
["./time-series-analysis-request.html","Request","Time series analyses are based on time series analysis requests that give the Data Analysis Service what data to process and how to process that d...","./images/zoomimage.jpg"],
["./time-series-storage.html","Time Series Storage","Enter topic text here.",""],
["./time-synchronization.html","Time synchronization","The Digital Twin Registration Agent uses an incremental approach when registering devices. I.e. it checks for changes in the provider DB regularly...","./images/zoomimage.jpg"],
["./time-to-live.html","Time to live","Tasks can have a time to live. This is a time span given in days that defines how long the Cloud To Device Distribution Service shall try to fulfi...","./images/zoomimage.jpg"],
["./total-online-time.html","Total online time","Whenever the Data Link Monitoring Service detects a change in the data link status from online to offline, temporarily offline or not connected it...","./images/zoomimage.jpg"],
["./trace_product.html","TRACE_Product","Description of columns Column Name Description SerialNo The serial number of the product assigned by the End-Test.  In fact the serial number...","./images/zoomimage.jpg"],
["./transmission-mode.html","Latest transmission mode","Devices can transmit value on occasion (typical for mobile gateways) or as result of a trigger event like a dispense action (typical for devices c...",""],
["./typographic_conventions.html","Typographic conventions","The following typographic conventions are used in this Reference Manual.","./images/zoomimage.jpg"],
["./updating.html","Updating","Updating the Digital Twin Registration Agent is done by replacing all the files int he program directory with the files of the new version - just ...","./images/zoomimage.jpg"],
["./v1.html","Version 1","Version 1 serial numbers are of variable length. Serial numbers of this version match the Regex ([0-9]{2})(0[0-9]&#124;1[012])([012][0-9]&#124;3[01])([0-9]{...",""],
["./v2.html","Version 2","Version 2 serial numbers are of fixed length. Serial numbers of this version match the regex (2[0-9]{3})-([0-9]{2})(0[0-9]&#124;1[012])([012][0-9]&#124;3[01...",""],
["./v3.html","Version 3","Version 3 of HsM serial numbers are fixed length serial numbers. This serial number contains digits and letters. The serial number is case insensi...",""],
["./validating-device-filters.html","Validating device filters","The HsM Client Service provides the possibility to validate a device filter and report the result so this validation in a human readable way. This...",""],
["./visibility.html","Visibility","Some information managed in the Catalog Service is marked with a visibility attribute. This visibility attribute is a hint to other systems using ...","./images/zoomimage.jpg"],
["./web-portal.html","Web portal","Enter topic text here.",""],
["./webp.html","Web portal","Enter topic text here.","./images/zoomimage.jpg"],
["./wizards.html","Wizards","A wizard in HSM is a user interface that presents a user with a sequence of views that leads the user through a series of steps. In HSM wizards ar...","./images/zoomimage.jpg"],
["./wording.html","Wording","Wording in Catalog: Compound device type: Device type with at least one device type placeholder. Compound member device type: Device type that can...","./images/zoomimage.jpg"],
["./working-directory.html","Working directory","The DTRA will create a working directory within the configured  DTRA_CONFIG_DIR the name of the working directory will be data.&#60;environmen...","./images/zoomimage.jpg"],
["./xiap.html","Xibu App","Enter topic text here.","./images/zoomimage.jpg"],
["./xibu-app.html","Xibu App","Enter topic text here.",""]];
